version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    container_name: kafka
    ports:
     - 9092:9092
    depends_on:
     - zookeeper
    links:
     - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
  postgres:
    image: debezium/postgres:13
    container_name: postgres
    ports:
     - 5050:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=exampledb
  test-db:
    image: debezium/postgres:13
    container_name: test-db
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=docker
     - POSTGRES_PASSWORD=docker
     - POSTGRES_DB=exampledb
  connect:
    image: debezium/connect-jdbc-es:1.4
    container_name: connect
    build:
      context: debezium-jdbc-es
    ports:
     - 8083:8083
     - 5005:5005
    depends_on:
     - kafka
    links:
     - kafka
     - test-db
     - postgres
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID="neuroai-1"
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses